Repository AY2324S1-CS2103T-F10-3/tp, pull requests merged in 2023-11, with the labels that each got.

#107 Add search command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/InventoryAppParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/recipe/RecipeIngredientNameMatchesPredicate.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: enhancement

#108 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
Labels: documentation

#110 Branch UI part3
  docs/images/Ui.png
  src/main/java/seedu/address/ui/FullRecipePanel.java
  src/main/java/seedu/address/ui/RecipeListCard.java
  src/main/java/seedu/address/ui/RecipeListPanel.java
  src/main/resources/view/FullRecipePanel.fxml
  src/main/resources/view/IngredientListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: bug, documentation

#115 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: documentation

#160 Branch update documentation
  docs/UserGuide.md
  docs/site.json
Labels: documentation

#168 Branch documentation
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/team/itstytan.md
Labels: documentation

#171 Update documentation
  docs/DeveloperGuide.md
  docs/diagrams/SearchRecipeSequenceDiagram.puml
  docs/images/UML/searchrecipesequencediagram.png
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#175 Update DG to include planned enhancements
  docs/DeveloperGuide.md
  docs/team/prawnzyy.md
Labels: documentation

#176 Update PPP and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/itstytan.md
Labels: documentation
