Repository AY2324S1-CS2103T-F10-3/tp, pull requests merged in 2023-10, with the labels that each got.

#57 Update name
  build.gradle
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#59 Enhance UI mockup
  docs/images/Ui.png
Labels: bug, documentation, enhancement

#77 Add second screen to main window
  src/main/java/seedu/address/ui/FullRecipeCard.java
  src/main/java/seedu/address/ui/FullRecipeListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecipeCard.java
  src/main/java/seedu/address/ui/RecipeListPanel.java
  src/main/resources/view/FullRecipeListCard.fxml
  src/main/resources/view/FullRecipeListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecipeListCard.fxml
  src/main/resources/view/RecipeListPanel.fxml
Labels: enhancement

#78 Update UI
  docs/images/Ui.png
Labels: enhancement

#79 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#83 Update UI to accept recipe model
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecipeCard.java
  src/main/java/seedu/address/ui/RecipeListPanel.java
Labels: enhancement

#84 Add recipe view command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/RecipeViewCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/parser/InventoryAppParser.java
  src/main/java/seedu/address/logic/parser/RecipeViewCommandParser.java
  src/main/java/seedu/address/model/recipe/RecipeUuidMatchesPredicate.java
Labels: enhancement

#103 Update UG
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/ui/RecipeListCard.java
Labels: documentation

#106 Add tests and bugfixes
  src/main/java/seedu/address/logic/commands/RecipeViewCommand.java
  src/main/java/seedu/address/logic/parser/RecipeViewCommandParser.java
  src/main/java/seedu/address/model/recipe/RecipeUuidMatchesPredicate.java
  src/main/java/seedu/address/model/recipe/UniqueId.java
  src/test/java/seedu/address/logic/commands/RecipeViewCommandTest.java
  src/test/java/seedu/address/logic/parser/RecipeViewCommandParserTest.java
Labels: bug
